name: " (beta)"
packageKey: "-beta"
description: "This driver extends the basic zwave functionality to include additional vendor specific parameters"
vendorSupportInformation: >-
   'This driver require a documented device to work properly.<br /><br />
    <a href="">SmartThings Community discussion</a><br /><br />
    <a href="/blob/main/README.md">GitHub Repository</a>'
permissions:
  zwave: {}
